// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: mumble.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace MumbleProto
{

    [global::ProtoBuf.ProtoContract()]
    public partial class Version : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public uint version
        {
            get { return __pbn__version.GetValueOrDefault(); }
            set { __pbn__version = value; }
        }
        public bool ShouldSerializeversion() => __pbn__version != null;
        public void Resetversion() => __pbn__version = null;
        private uint? __pbn__version;

        [global::ProtoBuf.ProtoMember(2, Name = @"release")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Release
        {
            get { return __pbn__Release ?? ""; }
            set { __pbn__Release = value; }
        }
        public bool ShouldSerializeRelease() => __pbn__Release != null;
        public void ResetRelease() => __pbn__Release = null;
        private string __pbn__Release;

        [global::ProtoBuf.ProtoMember(3, Name = @"os")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Os
        {
            get { return __pbn__Os ?? ""; }
            set { __pbn__Os = value; }
        }
        public bool ShouldSerializeOs() => __pbn__Os != null;
        public void ResetOs() => __pbn__Os = null;
        private string __pbn__Os;

        [global::ProtoBuf.ProtoMember(4, Name = @"os_version")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OsVersion
        {
            get { return __pbn__OsVersion ?? ""; }
            set { __pbn__OsVersion = value; }
        }
        public bool ShouldSerializeOsVersion() => __pbn__OsVersion != null;
        public void ResetOsVersion() => __pbn__OsVersion = null;
        private string __pbn__OsVersion;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UDPTunnel : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"packet", IsRequired = true)]
        public byte[] Packet { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Authenticate : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"username")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Username
        {
            get { return __pbn__Username ?? ""; }
            set { __pbn__Username = value; }
        }
        public bool ShouldSerializeUsername() => __pbn__Username != null;
        public void ResetUsername() => __pbn__Username = null;
        private string __pbn__Username;

        [global::ProtoBuf.ProtoMember(2, Name = @"password")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Password
        {
            get { return __pbn__Password ?? ""; }
            set { __pbn__Password = value; }
        }
        public bool ShouldSerializePassword() => __pbn__Password != null;
        public void ResetPassword() => __pbn__Password = null;
        private string __pbn__Password;

        [global::ProtoBuf.ProtoMember(3, Name = @"tokens")]
        public global::System.Collections.Generic.List<string> Tokens { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(4, Name = @"celt_versions")]
        public int[] CeltVersions { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"opus")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool Opus
        {
            get { return __pbn__Opus ?? false; }
            set { __pbn__Opus = value; }
        }
        public bool ShouldSerializeOpus() => __pbn__Opus != null;
        public void ResetOpus() => __pbn__Opus = null;
        private bool? __pbn__Opus;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Ping : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"timestamp")]
        public ulong Timestamp
        {
            get { return __pbn__Timestamp.GetValueOrDefault(); }
            set { __pbn__Timestamp = value; }
        }
        public bool ShouldSerializeTimestamp() => __pbn__Timestamp != null;
        public void ResetTimestamp() => __pbn__Timestamp = null;
        private ulong? __pbn__Timestamp;

        [global::ProtoBuf.ProtoMember(2, Name = @"good")]
        public uint Good
        {
            get { return __pbn__Good.GetValueOrDefault(); }
            set { __pbn__Good = value; }
        }
        public bool ShouldSerializeGood() => __pbn__Good != null;
        public void ResetGood() => __pbn__Good = null;
        private uint? __pbn__Good;

        [global::ProtoBuf.ProtoMember(3, Name = @"late")]
        public uint Late
        {
            get { return __pbn__Late.GetValueOrDefault(); }
            set { __pbn__Late = value; }
        }
        public bool ShouldSerializeLate() => __pbn__Late != null;
        public void ResetLate() => __pbn__Late = null;
        private uint? __pbn__Late;

        [global::ProtoBuf.ProtoMember(4, Name = @"lost")]
        public uint Lost
        {
            get { return __pbn__Lost.GetValueOrDefault(); }
            set { __pbn__Lost = value; }
        }
        public bool ShouldSerializeLost() => __pbn__Lost != null;
        public void ResetLost() => __pbn__Lost = null;
        private uint? __pbn__Lost;

        [global::ProtoBuf.ProtoMember(5, Name = @"resync")]
        public uint Resync
        {
            get { return __pbn__Resync.GetValueOrDefault(); }
            set { __pbn__Resync = value; }
        }
        public bool ShouldSerializeResync() => __pbn__Resync != null;
        public void ResetResync() => __pbn__Resync = null;
        private uint? __pbn__Resync;

        [global::ProtoBuf.ProtoMember(6, Name = @"udp_packets")]
        public uint UdpPackets
        {
            get { return __pbn__UdpPackets.GetValueOrDefault(); }
            set { __pbn__UdpPackets = value; }
        }
        public bool ShouldSerializeUdpPackets() => __pbn__UdpPackets != null;
        public void ResetUdpPackets() => __pbn__UdpPackets = null;
        private uint? __pbn__UdpPackets;

        [global::ProtoBuf.ProtoMember(7, Name = @"tcp_packets")]
        public uint TcpPackets
        {
            get { return __pbn__TcpPackets.GetValueOrDefault(); }
            set { __pbn__TcpPackets = value; }
        }
        public bool ShouldSerializeTcpPackets() => __pbn__TcpPackets != null;
        public void ResetTcpPackets() => __pbn__TcpPackets = null;
        private uint? __pbn__TcpPackets;

        [global::ProtoBuf.ProtoMember(8, Name = @"udp_ping_avg")]
        public float UdpPingAvg
        {
            get { return __pbn__UdpPingAvg.GetValueOrDefault(); }
            set { __pbn__UdpPingAvg = value; }
        }
        public bool ShouldSerializeUdpPingAvg() => __pbn__UdpPingAvg != null;
        public void ResetUdpPingAvg() => __pbn__UdpPingAvg = null;
        private float? __pbn__UdpPingAvg;

        [global::ProtoBuf.ProtoMember(9, Name = @"udp_ping_var")]
        public float UdpPingVar
        {
            get { return __pbn__UdpPingVar.GetValueOrDefault(); }
            set { __pbn__UdpPingVar = value; }
        }
        public bool ShouldSerializeUdpPingVar() => __pbn__UdpPingVar != null;
        public void ResetUdpPingVar() => __pbn__UdpPingVar = null;
        private float? __pbn__UdpPingVar;

        [global::ProtoBuf.ProtoMember(10, Name = @"tcp_ping_avg")]
        public float TcpPingAvg
        {
            get { return __pbn__TcpPingAvg.GetValueOrDefault(); }
            set { __pbn__TcpPingAvg = value; }
        }
        public bool ShouldSerializeTcpPingAvg() => __pbn__TcpPingAvg != null;
        public void ResetTcpPingAvg() => __pbn__TcpPingAvg = null;
        private float? __pbn__TcpPingAvg;

        [global::ProtoBuf.ProtoMember(11, Name = @"tcp_ping_var")]
        public float TcpPingVar
        {
            get { return __pbn__TcpPingVar.GetValueOrDefault(); }
            set { __pbn__TcpPingVar = value; }
        }
        public bool ShouldSerializeTcpPingVar() => __pbn__TcpPingVar != null;
        public void ResetTcpPingVar() => __pbn__TcpPingVar = null;
        private float? __pbn__TcpPingVar;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Reject : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(RejectType.None)]
        public RejectType Type
        {
            get { return __pbn__Type ?? RejectType.None; }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private RejectType? __pbn__Type;

        [global::ProtoBuf.ProtoMember(2, Name = @"reason")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason
        {
            get { return __pbn__Reason ?? ""; }
            set { __pbn__Reason = value; }
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private string __pbn__Reason;

        [global::ProtoBuf.ProtoContract()]
        public enum RejectType
        {
            None = 0,
            WrongVersion = 1,
            InvalidUsername = 2,
            WrongUserPW = 3,
            WrongServerPW = 4,
            UsernameInUse = 5,
            ServerFull = 6,
            NoCertificate = 7,
            AuthenticatorFail = 8,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerSync : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session")]
        public uint Session
        {
            get { return __pbn__Session.GetValueOrDefault(); }
            set { __pbn__Session = value; }
        }
        public bool ShouldSerializeSession() => __pbn__Session != null;
        public void ResetSession() => __pbn__Session = null;
        private uint? __pbn__Session;

        [global::ProtoBuf.ProtoMember(2, Name = @"max_bandwidth")]
        public uint MaxBandwidth
        {
            get { return __pbn__MaxBandwidth.GetValueOrDefault(); }
            set { __pbn__MaxBandwidth = value; }
        }
        public bool ShouldSerializeMaxBandwidth() => __pbn__MaxBandwidth != null;
        public void ResetMaxBandwidth() => __pbn__MaxBandwidth = null;
        private uint? __pbn__MaxBandwidth;

        [global::ProtoBuf.ProtoMember(3, Name = @"welcome_text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string WelcomeText
        {
            get { return __pbn__WelcomeText ?? ""; }
            set { __pbn__WelcomeText = value; }
        }
        public bool ShouldSerializeWelcomeText() => __pbn__WelcomeText != null;
        public void ResetWelcomeText() => __pbn__WelcomeText = null;
        private string __pbn__WelcomeText;

        [global::ProtoBuf.ProtoMember(4, Name = @"permissions")]
        public ulong Permissions
        {
            get { return __pbn__Permissions.GetValueOrDefault(); }
            set { __pbn__Permissions = value; }
        }
        public bool ShouldSerializePermissions() => __pbn__Permissions != null;
        public void ResetPermissions() => __pbn__Permissions = null;
        private ulong? __pbn__Permissions;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChannelRemove : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"channel_id", IsRequired = true)]
        public uint ChannelId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChannelState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"channel_id")]
        public uint ChannelId
        {
            get { return __pbn__ChannelId.GetValueOrDefault(); }
            set { __pbn__ChannelId = value; }
        }
        public bool ShouldSerializeChannelId() => __pbn__ChannelId != null;
        public void ResetChannelId() => __pbn__ChannelId = null;
        private uint? __pbn__ChannelId;

        [global::ProtoBuf.ProtoMember(2, Name = @"parent")]
        public uint Parent
        {
            get { return __pbn__Parent.GetValueOrDefault(); }
            set { __pbn__Parent = value; }
        }
        public bool ShouldSerializeParent() => __pbn__Parent != null;
        public void ResetParent() => __pbn__Parent = null;
        private uint? __pbn__Parent;

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(4, Name = @"links")]
        public uint[] Links { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description
        {
            get { return __pbn__Description ?? ""; }
            set { __pbn__Description = value; }
        }
        public bool ShouldSerializeDescription() => __pbn__Description != null;
        public void ResetDescription() => __pbn__Description = null;
        private string __pbn__Description;

        [global::ProtoBuf.ProtoMember(6, Name = @"links_add")]
        public uint[] LinksAdds { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"links_remove")]
        public uint[] LinksRemoves { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"temporary")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool Temporary
        {
            get { return __pbn__Temporary ?? false; }
            set { __pbn__Temporary = value; }
        }
        public bool ShouldSerializeTemporary() => __pbn__Temporary != null;
        public void ResetTemporary() => __pbn__Temporary = null;
        private bool? __pbn__Temporary;

        [global::ProtoBuf.ProtoMember(9, Name = @"position")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int Position
        {
            get { return __pbn__Position ?? 0; }
            set { __pbn__Position = value; }
        }
        public bool ShouldSerializePosition() => __pbn__Position != null;
        public void ResetPosition() => __pbn__Position = null;
        private int? __pbn__Position;

        [global::ProtoBuf.ProtoMember(10, Name = @"description_hash")]
        public byte[] DescriptionHash
        {
            get { return __pbn__DescriptionHash; }
            set { __pbn__DescriptionHash = value; }
        }
        public bool ShouldSerializeDescriptionHash() => __pbn__DescriptionHash != null;
        public void ResetDescriptionHash() => __pbn__DescriptionHash = null;
        private byte[] __pbn__DescriptionHash;

        [global::ProtoBuf.ProtoMember(11, Name = @"max_users")]
        public uint MaxUsers
        {
            get { return __pbn__MaxUsers.GetValueOrDefault(); }
            set { __pbn__MaxUsers = value; }
        }
        public bool ShouldSerializeMaxUsers() => __pbn__MaxUsers != null;
        public void ResetMaxUsers() => __pbn__MaxUsers = null;
        private uint? __pbn__MaxUsers;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserRemove : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session", IsRequired = true)]
        public uint Session { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"actor")]
        public uint Actor
        {
            get { return __pbn__Actor.GetValueOrDefault(); }
            set { __pbn__Actor = value; }
        }
        public bool ShouldSerializeActor() => __pbn__Actor != null;
        public void ResetActor() => __pbn__Actor = null;
        private uint? __pbn__Actor;

        [global::ProtoBuf.ProtoMember(3, Name = @"reason")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason
        {
            get { return __pbn__Reason ?? ""; }
            set { __pbn__Reason = value; }
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private string __pbn__Reason;

        [global::ProtoBuf.ProtoMember(4, Name = @"ban")]
        public bool Ban
        {
            get { return __pbn__Ban.GetValueOrDefault(); }
            set { __pbn__Ban = value; }
        }
        public bool ShouldSerializeBan() => __pbn__Ban != null;
        public void ResetBan() => __pbn__Ban = null;
        private bool? __pbn__Ban;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserState : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session")]
        public uint Session
        {
            get { return __pbn__Session.GetValueOrDefault(); }
            set { __pbn__Session = value; }
        }
        public bool ShouldSerializeSession() => __pbn__Session != null;
        public void ResetSession() => __pbn__Session = null;
        private uint? __pbn__Session;

        [global::ProtoBuf.ProtoMember(2, Name = @"actor")]
        public uint Actor
        {
            get { return __pbn__Actor.GetValueOrDefault(); }
            set { __pbn__Actor = value; }
        }
        public bool ShouldSerializeActor() => __pbn__Actor != null;
        public void ResetActor() => __pbn__Actor = null;
        private uint? __pbn__Actor;

        [global::ProtoBuf.ProtoMember(3, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(4, Name = @"user_id")]
        public uint UserId
        {
            get { return __pbn__UserId.GetValueOrDefault(); }
            set { __pbn__UserId = value; }
        }
        public bool ShouldSerializeUserId() => __pbn__UserId != null;
        public void ResetUserId() => __pbn__UserId = null;
        private uint? __pbn__UserId;

        [global::ProtoBuf.ProtoMember(5, Name = @"channel_id")]
        public uint ChannelId
        {
            get { return __pbn__ChannelId.GetValueOrDefault(); }
            set { __pbn__ChannelId = value; }
        }
        public bool ShouldSerializeChannelId() => __pbn__ChannelId != null;
        public void ResetChannelId() => __pbn__ChannelId = null;
        private uint? __pbn__ChannelId;

        [global::ProtoBuf.ProtoMember(6, Name = @"mute")]
        public bool Mute
        {
            get { return __pbn__Mute.GetValueOrDefault(); }
            set { __pbn__Mute = value; }
        }
        public bool ShouldSerializeMute() => __pbn__Mute != null;
        public void ResetMute() => __pbn__Mute = null;
        private bool? __pbn__Mute;

        [global::ProtoBuf.ProtoMember(7, Name = @"deaf")]
        public bool Deaf
        {
            get { return __pbn__Deaf.GetValueOrDefault(); }
            set { __pbn__Deaf = value; }
        }
        public bool ShouldSerializeDeaf() => __pbn__Deaf != null;
        public void ResetDeaf() => __pbn__Deaf = null;
        private bool? __pbn__Deaf;

        [global::ProtoBuf.ProtoMember(8, Name = @"suppress")]
        public bool Suppress
        {
            get { return __pbn__Suppress.GetValueOrDefault(); }
            set { __pbn__Suppress = value; }
        }
        public bool ShouldSerializeSuppress() => __pbn__Suppress != null;
        public void ResetSuppress() => __pbn__Suppress = null;
        private bool? __pbn__Suppress;

        [global::ProtoBuf.ProtoMember(9, Name = @"self_mute")]
        public bool SelfMute
        {
            get { return __pbn__SelfMute.GetValueOrDefault(); }
            set { __pbn__SelfMute = value; }
        }
        public bool ShouldSerializeSelfMute() => __pbn__SelfMute != null;
        public void ResetSelfMute() => __pbn__SelfMute = null;
        private bool? __pbn__SelfMute;

        [global::ProtoBuf.ProtoMember(10, Name = @"self_deaf")]
        public bool SelfDeaf
        {
            get { return __pbn__SelfDeaf.GetValueOrDefault(); }
            set { __pbn__SelfDeaf = value; }
        }
        public bool ShouldSerializeSelfDeaf() => __pbn__SelfDeaf != null;
        public void ResetSelfDeaf() => __pbn__SelfDeaf = null;
        private bool? __pbn__SelfDeaf;

        [global::ProtoBuf.ProtoMember(11, Name = @"texture")]
        public byte[] Texture
        {
            get { return __pbn__Texture; }
            set { __pbn__Texture = value; }
        }
        public bool ShouldSerializeTexture() => __pbn__Texture != null;
        public void ResetTexture() => __pbn__Texture = null;
        private byte[] __pbn__Texture;

        [global::ProtoBuf.ProtoMember(12, Name = @"plugin_context")]
        public byte[] PluginContext
        {
            get { return __pbn__PluginContext; }
            set { __pbn__PluginContext = value; }
        }
        public bool ShouldSerializePluginContext() => __pbn__PluginContext != null;
        public void ResetPluginContext() => __pbn__PluginContext = null;
        private byte[] __pbn__PluginContext;

        [global::ProtoBuf.ProtoMember(13, Name = @"plugin_identity")]
        [global::System.ComponentModel.DefaultValue("")]
        public string PluginIdentity
        {
            get { return __pbn__PluginIdentity ?? ""; }
            set { __pbn__PluginIdentity = value; }
        }
        public bool ShouldSerializePluginIdentity() => __pbn__PluginIdentity != null;
        public void ResetPluginIdentity() => __pbn__PluginIdentity = null;
        private string __pbn__PluginIdentity;

        [global::ProtoBuf.ProtoMember(14, Name = @"comment")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Comment
        {
            get { return __pbn__Comment ?? ""; }
            set { __pbn__Comment = value; }
        }
        public bool ShouldSerializeComment() => __pbn__Comment != null;
        public void ResetComment() => __pbn__Comment = null;
        private string __pbn__Comment;

        [global::ProtoBuf.ProtoMember(15, Name = @"hash")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Hash
        {
            get { return __pbn__Hash ?? ""; }
            set { __pbn__Hash = value; }
        }
        public bool ShouldSerializeHash() => __pbn__Hash != null;
        public void ResetHash() => __pbn__Hash = null;
        private string __pbn__Hash;

        [global::ProtoBuf.ProtoMember(16, Name = @"comment_hash")]
        public byte[] CommentHash
        {
            get { return __pbn__CommentHash; }
            set { __pbn__CommentHash = value; }
        }
        public bool ShouldSerializeCommentHash() => __pbn__CommentHash != null;
        public void ResetCommentHash() => __pbn__CommentHash = null;
        private byte[] __pbn__CommentHash;

        [global::ProtoBuf.ProtoMember(17, Name = @"texture_hash")]
        public byte[] TextureHash
        {
            get { return __pbn__TextureHash; }
            set { __pbn__TextureHash = value; }
        }
        public bool ShouldSerializeTextureHash() => __pbn__TextureHash != null;
        public void ResetTextureHash() => __pbn__TextureHash = null;
        private byte[] __pbn__TextureHash;

        [global::ProtoBuf.ProtoMember(18, Name = @"priority_speaker")]
        public bool PrioritySpeaker
        {
            get { return __pbn__PrioritySpeaker.GetValueOrDefault(); }
            set { __pbn__PrioritySpeaker = value; }
        }
        public bool ShouldSerializePrioritySpeaker() => __pbn__PrioritySpeaker != null;
        public void ResetPrioritySpeaker() => __pbn__PrioritySpeaker = null;
        private bool? __pbn__PrioritySpeaker;

        [global::ProtoBuf.ProtoMember(19, Name = @"recording")]
        public bool Recording
        {
            get { return __pbn__Recording.GetValueOrDefault(); }
            set { __pbn__Recording = value; }
        }
        public bool ShouldSerializeRecording() => __pbn__Recording != null;
        public void ResetRecording() => __pbn__Recording = null;
        private bool? __pbn__Recording;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BanList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"bans")]
        public global::System.Collections.Generic.List<BanEntry> Bans { get; } = new global::System.Collections.Generic.List<BanEntry>();

        [global::ProtoBuf.ProtoMember(2, Name = @"query")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool Query
        {
            get { return __pbn__Query ?? false; }
            set { __pbn__Query = value; }
        }
        public bool ShouldSerializeQuery() => __pbn__Query != null;
        public void ResetQuery() => __pbn__Query = null;
        private bool? __pbn__Query;

        [global::ProtoBuf.ProtoContract()]
        public partial class BanEntry : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"address", IsRequired = true)]
            public byte[] Address { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"mask", IsRequired = true)]
            public uint Mask { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name
            {
                get { return __pbn__Name ?? ""; }
                set { __pbn__Name = value; }
            }
            public bool ShouldSerializeName() => __pbn__Name != null;
            public void ResetName() => __pbn__Name = null;
            private string __pbn__Name;

            [global::ProtoBuf.ProtoMember(4, Name = @"hash")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Hash
            {
                get { return __pbn__Hash ?? ""; }
                set { __pbn__Hash = value; }
            }
            public bool ShouldSerializeHash() => __pbn__Hash != null;
            public void ResetHash() => __pbn__Hash = null;
            private string __pbn__Hash;

            [global::ProtoBuf.ProtoMember(5, Name = @"reason")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Reason
            {
                get { return __pbn__Reason ?? ""; }
                set { __pbn__Reason = value; }
            }
            public bool ShouldSerializeReason() => __pbn__Reason != null;
            public void ResetReason() => __pbn__Reason = null;
            private string __pbn__Reason;

            [global::ProtoBuf.ProtoMember(6, Name = @"start")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Start
            {
                get { return __pbn__Start ?? ""; }
                set { __pbn__Start = value; }
            }
            public bool ShouldSerializeStart() => __pbn__Start != null;
            public void ResetStart() => __pbn__Start = null;
            private string __pbn__Start;

            [global::ProtoBuf.ProtoMember(7, Name = @"duration")]
            public uint Duration
            {
                get { return __pbn__Duration.GetValueOrDefault(); }
                set { __pbn__Duration = value; }
            }
            public bool ShouldSerializeDuration() => __pbn__Duration != null;
            public void ResetDuration() => __pbn__Duration = null;
            private uint? __pbn__Duration;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TextMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"actor")]
        public uint Actor
        {
            get { return __pbn__Actor.GetValueOrDefault(); }
            set { __pbn__Actor = value; }
        }
        public bool ShouldSerializeActor() => __pbn__Actor != null;
        public void ResetActor() => __pbn__Actor = null;
        private uint? __pbn__Actor;

        [global::ProtoBuf.ProtoMember(2, Name = @"session")]
        public uint[] Sessions { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"channel_id")]
        public uint[] ChannelIds { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"tree_id")]
        public uint[] TreeIds { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"message", IsRequired = true)]
        public string Message { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PermissionDenied : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"permission")]
        public uint Permission
        {
            get { return __pbn__Permission.GetValueOrDefault(); }
            set { __pbn__Permission = value; }
        }
        public bool ShouldSerializePermission() => __pbn__Permission != null;
        public void ResetPermission() => __pbn__Permission = null;
        private uint? __pbn__Permission;

        [global::ProtoBuf.ProtoMember(2, Name = @"channel_id")]
        public uint ChannelId
        {
            get { return __pbn__ChannelId.GetValueOrDefault(); }
            set { __pbn__ChannelId = value; }
        }
        public bool ShouldSerializeChannelId() => __pbn__ChannelId != null;
        public void ResetChannelId() => __pbn__ChannelId = null;
        private uint? __pbn__ChannelId;

        [global::ProtoBuf.ProtoMember(3, Name = @"session")]
        public uint Session
        {
            get { return __pbn__Session.GetValueOrDefault(); }
            set { __pbn__Session = value; }
        }
        public bool ShouldSerializeSession() => __pbn__Session != null;
        public void ResetSession() => __pbn__Session = null;
        private uint? __pbn__Session;

        [global::ProtoBuf.ProtoMember(4, Name = @"reason")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Reason
        {
            get { return __pbn__Reason ?? ""; }
            set { __pbn__Reason = value; }
        }
        public bool ShouldSerializeReason() => __pbn__Reason != null;
        public void ResetReason() => __pbn__Reason = null;
        private string __pbn__Reason;

        [global::ProtoBuf.ProtoMember(5, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(DenyType.Text)]
        public DenyType Type
        {
            get { return __pbn__Type ?? DenyType.Text; }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private DenyType? __pbn__Type;

        [global::ProtoBuf.ProtoMember(6, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoContract()]
        public enum DenyType
        {
            Text = 0,
            Permission = 1,
            SuperUser = 2,
            ChannelName = 3,
            TextTooLong = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"H9K")]
            H9k = 5,
            TemporaryChannel = 6,
            MissingCertificate = 7,
            UserName = 8,
            ChannelFull = 9,
            NestingLimit = 10,
        }

    }

    [global::ProtoBuf.ProtoContract(Name = @"ACL")]
    public partial class Acl : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"channel_id", IsRequired = true)]
        public uint ChannelId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"inherit_acls")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool InheritAcls
        {
            get { return __pbn__InheritAcls ?? true; }
            set { __pbn__InheritAcls = value; }
        }
        public bool ShouldSerializeInheritAcls() => __pbn__InheritAcls != null;
        public void ResetInheritAcls() => __pbn__InheritAcls = null;
        private bool? __pbn__InheritAcls;

        [global::ProtoBuf.ProtoMember(3, Name = @"groups")]
        public global::System.Collections.Generic.List<ChanGroup> Groups { get; } = new global::System.Collections.Generic.List<ChanGroup>();

        [global::ProtoBuf.ProtoMember(4, Name = @"acls")]
        public global::System.Collections.Generic.List<ChanACL> Acls { get; } = new global::System.Collections.Generic.List<ChanACL>();

        [global::ProtoBuf.ProtoMember(5, Name = @"query")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool Query
        {
            get { return __pbn__Query ?? false; }
            set { __pbn__Query = value; }
        }
        public bool ShouldSerializeQuery() => __pbn__Query != null;
        public void ResetQuery() => __pbn__Query = null;
        private bool? __pbn__Query;

        [global::ProtoBuf.ProtoContract()]
        public partial class ChanGroup : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"name", IsRequired = true)]
            public string Name { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"inherited")]
            [global::System.ComponentModel.DefaultValue(true)]
            public bool Inherited
            {
                get { return __pbn__Inherited ?? true; }
                set { __pbn__Inherited = value; }
            }
            public bool ShouldSerializeInherited() => __pbn__Inherited != null;
            public void ResetInherited() => __pbn__Inherited = null;
            private bool? __pbn__Inherited;

            [global::ProtoBuf.ProtoMember(3, Name = @"inherit")]
            [global::System.ComponentModel.DefaultValue(true)]
            public bool Inherit
            {
                get { return __pbn__Inherit ?? true; }
                set { __pbn__Inherit = value; }
            }
            public bool ShouldSerializeInherit() => __pbn__Inherit != null;
            public void ResetInherit() => __pbn__Inherit = null;
            private bool? __pbn__Inherit;

            [global::ProtoBuf.ProtoMember(4, Name = @"inheritable")]
            [global::System.ComponentModel.DefaultValue(true)]
            public bool Inheritable
            {
                get { return __pbn__Inheritable ?? true; }
                set { __pbn__Inheritable = value; }
            }
            public bool ShouldSerializeInheritable() => __pbn__Inheritable != null;
            public void ResetInheritable() => __pbn__Inheritable = null;
            private bool? __pbn__Inheritable;

            [global::ProtoBuf.ProtoMember(5, Name = @"add")]
            public uint[] Adds { get; set; }

            [global::ProtoBuf.ProtoMember(6, Name = @"remove")]
            public uint[] Removes { get; set; }

            [global::ProtoBuf.ProtoMember(7, Name = @"inherited_members")]
            public uint[] InheritedMembers { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class ChanACL : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"apply_here")]
            [global::System.ComponentModel.DefaultValue(true)]
            public bool ApplyHere
            {
                get { return __pbn__ApplyHere ?? true; }
                set { __pbn__ApplyHere = value; }
            }
            public bool ShouldSerializeApplyHere() => __pbn__ApplyHere != null;
            public void ResetApplyHere() => __pbn__ApplyHere = null;
            private bool? __pbn__ApplyHere;

            [global::ProtoBuf.ProtoMember(2, Name = @"apply_subs")]
            [global::System.ComponentModel.DefaultValue(true)]
            public bool ApplySubs
            {
                get { return __pbn__ApplySubs ?? true; }
                set { __pbn__ApplySubs = value; }
            }
            public bool ShouldSerializeApplySubs() => __pbn__ApplySubs != null;
            public void ResetApplySubs() => __pbn__ApplySubs = null;
            private bool? __pbn__ApplySubs;

            [global::ProtoBuf.ProtoMember(3, Name = @"inherited")]
            [global::System.ComponentModel.DefaultValue(true)]
            public bool Inherited
            {
                get { return __pbn__Inherited ?? true; }
                set { __pbn__Inherited = value; }
            }
            public bool ShouldSerializeInherited() => __pbn__Inherited != null;
            public void ResetInherited() => __pbn__Inherited = null;
            private bool? __pbn__Inherited;

            [global::ProtoBuf.ProtoMember(4, Name = @"user_id")]
            public uint UserId
            {
                get { return __pbn__UserId.GetValueOrDefault(); }
                set { __pbn__UserId = value; }
            }
            public bool ShouldSerializeUserId() => __pbn__UserId != null;
            public void ResetUserId() => __pbn__UserId = null;
            private uint? __pbn__UserId;

            [global::ProtoBuf.ProtoMember(5, Name = @"group")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Group
            {
                get { return __pbn__Group ?? ""; }
                set { __pbn__Group = value; }
            }
            public bool ShouldSerializeGroup() => __pbn__Group != null;
            public void ResetGroup() => __pbn__Group = null;
            private string __pbn__Group;

            [global::ProtoBuf.ProtoMember(6, Name = @"grant")]
            public uint Grant
            {
                get { return __pbn__Grant.GetValueOrDefault(); }
                set { __pbn__Grant = value; }
            }
            public bool ShouldSerializeGrant() => __pbn__Grant != null;
            public void ResetGrant() => __pbn__Grant = null;
            private uint? __pbn__Grant;

            [global::ProtoBuf.ProtoMember(7, Name = @"deny")]
            public uint Deny
            {
                get { return __pbn__Deny.GetValueOrDefault(); }
                set { __pbn__Deny = value; }
            }
            public bool ShouldSerializeDeny() => __pbn__Deny != null;
            public void ResetDeny() => __pbn__Deny = null;
            private uint? __pbn__Deny;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class QueryUsers : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"ids")]
        public uint[] Ids { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"names")]
        public global::System.Collections.Generic.List<string> Names { get; } = new global::System.Collections.Generic.List<string>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CryptSetup : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key")]
        public byte[] Key
        {
            get { return __pbn__Key; }
            set { __pbn__Key = value; }
        }
        public bool ShouldSerializeKey() => __pbn__Key != null;
        public void ResetKey() => __pbn__Key = null;
        private byte[] __pbn__Key;

        [global::ProtoBuf.ProtoMember(2, Name = @"client_nonce")]
        public byte[] ClientNonce
        {
            get { return __pbn__ClientNonce; }
            set { __pbn__ClientNonce = value; }
        }
        public bool ShouldSerializeClientNonce() => __pbn__ClientNonce != null;
        public void ResetClientNonce() => __pbn__ClientNonce = null;
        private byte[] __pbn__ClientNonce;

        [global::ProtoBuf.ProtoMember(3, Name = @"server_nonce")]
        public byte[] ServerNonce
        {
            get { return __pbn__ServerNonce; }
            set { __pbn__ServerNonce = value; }
        }
        public bool ShouldSerializeServerNonce() => __pbn__ServerNonce != null;
        public void ResetServerNonce() => __pbn__ServerNonce = null;
        private byte[] __pbn__ServerNonce;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContextActionModify : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"action", IsRequired = true)]
        public string Action { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Text
        {
            get { return __pbn__Text ?? ""; }
            set { __pbn__Text = value; }
        }
        public bool ShouldSerializeText() => __pbn__Text != null;
        public void ResetText() => __pbn__Text = null;
        private string __pbn__Text;

        [global::ProtoBuf.ProtoMember(3)]
        public uint context
        {
            get { return __pbn__context.GetValueOrDefault(); }
            set { __pbn__context = value; }
        }
        public bool ShouldSerializecontext() => __pbn__context != null;
        public void Resetcontext() => __pbn__context = null;
        private uint? __pbn__context;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue(Operation.Add)]
        public Operation operation
        {
            get { return __pbn__operation ?? Operation.Add; }
            set { __pbn__operation = value; }
        }
        public bool ShouldSerializeoperation() => __pbn__operation != null;
        public void Resetoperation() => __pbn__operation = null;
        private Operation? __pbn__operation;

        [global::ProtoBuf.ProtoContract()]
        public enum Context
        {
            Server = 1,
            Channel = 2,
            User = 4,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum Operation
        {
            Add = 0,
            Remove = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContextAction : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session")]
        public uint Session
        {
            get { return __pbn__Session.GetValueOrDefault(); }
            set { __pbn__Session = value; }
        }
        public bool ShouldSerializeSession() => __pbn__Session != null;
        public void ResetSession() => __pbn__Session = null;
        private uint? __pbn__Session;

        [global::ProtoBuf.ProtoMember(2, Name = @"channel_id")]
        public uint ChannelId
        {
            get { return __pbn__ChannelId.GetValueOrDefault(); }
            set { __pbn__ChannelId = value; }
        }
        public bool ShouldSerializeChannelId() => __pbn__ChannelId != null;
        public void ResetChannelId() => __pbn__ChannelId = null;
        private uint? __pbn__ChannelId;

        [global::ProtoBuf.ProtoMember(3, Name = @"action", IsRequired = true)]
        public string Action { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"users")]
        public global::System.Collections.Generic.List<User> Users { get; } = new global::System.Collections.Generic.List<User>();

        [global::ProtoBuf.ProtoContract()]
        public partial class User : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"user_id", IsRequired = true)]
            public uint UserId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name
            {
                get { return __pbn__Name ?? ""; }
                set { __pbn__Name = value; }
            }
            public bool ShouldSerializeName() => __pbn__Name != null;
            public void ResetName() => __pbn__Name = null;
            private string __pbn__Name;

            [global::ProtoBuf.ProtoMember(3, Name = @"last_seen")]
            [global::System.ComponentModel.DefaultValue("")]
            public string LastSeen
            {
                get { return __pbn__LastSeen ?? ""; }
                set { __pbn__LastSeen = value; }
            }
            public bool ShouldSerializeLastSeen() => __pbn__LastSeen != null;
            public void ResetLastSeen() => __pbn__LastSeen = null;
            private string __pbn__LastSeen;

            [global::ProtoBuf.ProtoMember(4, Name = @"last_channel")]
            public uint LastChannel
            {
                get { return __pbn__LastChannel.GetValueOrDefault(); }
                set { __pbn__LastChannel = value; }
            }
            public bool ShouldSerializeLastChannel() => __pbn__LastChannel != null;
            public void ResetLastChannel() => __pbn__LastChannel = null;
            private uint? __pbn__LastChannel;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VoiceTarget : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get { return __pbn__Id.GetValueOrDefault(); }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"targets")]
        public global::System.Collections.Generic.List<Target> Targets { get; } = new global::System.Collections.Generic.List<Target>();

        [global::ProtoBuf.ProtoContract()]
        public partial class Target : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"session")]
            public uint[] Sessions { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"channel_id")]
            public uint ChannelId
            {
                get { return __pbn__ChannelId.GetValueOrDefault(); }
                set { __pbn__ChannelId = value; }
            }
            public bool ShouldSerializeChannelId() => __pbn__ChannelId != null;
            public void ResetChannelId() => __pbn__ChannelId = null;
            private uint? __pbn__ChannelId;

            [global::ProtoBuf.ProtoMember(3, Name = @"group")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Group
            {
                get { return __pbn__Group ?? ""; }
                set { __pbn__Group = value; }
            }
            public bool ShouldSerializeGroup() => __pbn__Group != null;
            public void ResetGroup() => __pbn__Group = null;
            private string __pbn__Group;

            [global::ProtoBuf.ProtoMember(4, Name = @"links")]
            [global::System.ComponentModel.DefaultValue(false)]
            public bool Links
            {
                get { return __pbn__Links ?? false; }
                set { __pbn__Links = value; }
            }
            public bool ShouldSerializeLinks() => __pbn__Links != null;
            public void ResetLinks() => __pbn__Links = null;
            private bool? __pbn__Links;

            [global::ProtoBuf.ProtoMember(5, Name = @"children")]
            [global::System.ComponentModel.DefaultValue(false)]
            public bool Children
            {
                get { return __pbn__Children ?? false; }
                set { __pbn__Children = value; }
            }
            public bool ShouldSerializeChildren() => __pbn__Children != null;
            public void ResetChildren() => __pbn__Children = null;
            private bool? __pbn__Children;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PermissionQuery : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"channel_id")]
        public uint ChannelId
        {
            get { return __pbn__ChannelId.GetValueOrDefault(); }
            set { __pbn__ChannelId = value; }
        }
        public bool ShouldSerializeChannelId() => __pbn__ChannelId != null;
        public void ResetChannelId() => __pbn__ChannelId = null;
        private uint? __pbn__ChannelId;

        [global::ProtoBuf.ProtoMember(2, Name = @"permissions")]
        public uint Permissions
        {
            get { return __pbn__Permissions.GetValueOrDefault(); }
            set { __pbn__Permissions = value; }
        }
        public bool ShouldSerializePermissions() => __pbn__Permissions != null;
        public void ResetPermissions() => __pbn__Permissions = null;
        private uint? __pbn__Permissions;

        [global::ProtoBuf.ProtoMember(3, Name = @"flush")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool Flush
        {
            get { return __pbn__Flush ?? false; }
            set { __pbn__Flush = value; }
        }
        public bool ShouldSerializeFlush() => __pbn__Flush != null;
        public void ResetFlush() => __pbn__Flush = null;
        private bool? __pbn__Flush;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CodecVersion : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"alpha", IsRequired = true)]
        public int Alpha { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"beta", IsRequired = true)]
        public int Beta { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"prefer_alpha", IsRequired = true)]
        public bool PreferAlpha { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"opus")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool Opus
        {
            get { return __pbn__Opus ?? false; }
            set { __pbn__Opus = value; }
        }
        public bool ShouldSerializeOpus() => __pbn__Opus != null;
        public void ResetOpus() => __pbn__Opus = null;
        private bool? __pbn__Opus;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserStats : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session")]
        public uint Session
        {
            get { return __pbn__Session.GetValueOrDefault(); }
            set { __pbn__Session = value; }
        }
        public bool ShouldSerializeSession() => __pbn__Session != null;
        public void ResetSession() => __pbn__Session = null;
        private uint? __pbn__Session;

        [global::ProtoBuf.ProtoMember(2, Name = @"stats_only")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool StatsOnly
        {
            get { return __pbn__StatsOnly ?? false; }
            set { __pbn__StatsOnly = value; }
        }
        public bool ShouldSerializeStatsOnly() => __pbn__StatsOnly != null;
        public void ResetStatsOnly() => __pbn__StatsOnly = null;
        private bool? __pbn__StatsOnly;

        [global::ProtoBuf.ProtoMember(3, Name = @"certificates")]
        public global::System.Collections.Generic.List<byte[]> Certificates { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(4, Name = @"from_client")]
        public Stats FromClient { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"from_server")]
        public Stats FromServer { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"udp_packets")]
        public uint UdpPackets
        {
            get { return __pbn__UdpPackets.GetValueOrDefault(); }
            set { __pbn__UdpPackets = value; }
        }
        public bool ShouldSerializeUdpPackets() => __pbn__UdpPackets != null;
        public void ResetUdpPackets() => __pbn__UdpPackets = null;
        private uint? __pbn__UdpPackets;

        [global::ProtoBuf.ProtoMember(7, Name = @"tcp_packets")]
        public uint TcpPackets
        {
            get { return __pbn__TcpPackets.GetValueOrDefault(); }
            set { __pbn__TcpPackets = value; }
        }
        public bool ShouldSerializeTcpPackets() => __pbn__TcpPackets != null;
        public void ResetTcpPackets() => __pbn__TcpPackets = null;
        private uint? __pbn__TcpPackets;

        [global::ProtoBuf.ProtoMember(8, Name = @"udp_ping_avg")]
        public float UdpPingAvg
        {
            get { return __pbn__UdpPingAvg.GetValueOrDefault(); }
            set { __pbn__UdpPingAvg = value; }
        }
        public bool ShouldSerializeUdpPingAvg() => __pbn__UdpPingAvg != null;
        public void ResetUdpPingAvg() => __pbn__UdpPingAvg = null;
        private float? __pbn__UdpPingAvg;

        [global::ProtoBuf.ProtoMember(9, Name = @"udp_ping_var")]
        public float UdpPingVar
        {
            get { return __pbn__UdpPingVar.GetValueOrDefault(); }
            set { __pbn__UdpPingVar = value; }
        }
        public bool ShouldSerializeUdpPingVar() => __pbn__UdpPingVar != null;
        public void ResetUdpPingVar() => __pbn__UdpPingVar = null;
        private float? __pbn__UdpPingVar;

        [global::ProtoBuf.ProtoMember(10, Name = @"tcp_ping_avg")]
        public float TcpPingAvg
        {
            get { return __pbn__TcpPingAvg.GetValueOrDefault(); }
            set { __pbn__TcpPingAvg = value; }
        }
        public bool ShouldSerializeTcpPingAvg() => __pbn__TcpPingAvg != null;
        public void ResetTcpPingAvg() => __pbn__TcpPingAvg = null;
        private float? __pbn__TcpPingAvg;

        [global::ProtoBuf.ProtoMember(11, Name = @"tcp_ping_var")]
        public float TcpPingVar
        {
            get { return __pbn__TcpPingVar.GetValueOrDefault(); }
            set { __pbn__TcpPingVar = value; }
        }
        public bool ShouldSerializeTcpPingVar() => __pbn__TcpPingVar != null;
        public void ResetTcpPingVar() => __pbn__TcpPingVar = null;
        private float? __pbn__TcpPingVar;

        [global::ProtoBuf.ProtoMember(12, Name = @"version")]
        public Version Version { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"celt_versions")]
        public int[] CeltVersions { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"address")]
        public byte[] Address
        {
            get { return __pbn__Address; }
            set { __pbn__Address = value; }
        }
        public bool ShouldSerializeAddress() => __pbn__Address != null;
        public void ResetAddress() => __pbn__Address = null;
        private byte[] __pbn__Address;

        [global::ProtoBuf.ProtoMember(15, Name = @"bandwidth")]
        public uint Bandwidth
        {
            get { return __pbn__Bandwidth.GetValueOrDefault(); }
            set { __pbn__Bandwidth = value; }
        }
        public bool ShouldSerializeBandwidth() => __pbn__Bandwidth != null;
        public void ResetBandwidth() => __pbn__Bandwidth = null;
        private uint? __pbn__Bandwidth;

        [global::ProtoBuf.ProtoMember(16, Name = @"onlinesecs")]
        public uint Onlinesecs
        {
            get { return __pbn__Onlinesecs.GetValueOrDefault(); }
            set { __pbn__Onlinesecs = value; }
        }
        public bool ShouldSerializeOnlinesecs() => __pbn__Onlinesecs != null;
        public void ResetOnlinesecs() => __pbn__Onlinesecs = null;
        private uint? __pbn__Onlinesecs;

        [global::ProtoBuf.ProtoMember(17, Name = @"idlesecs")]
        public uint Idlesecs
        {
            get { return __pbn__Idlesecs.GetValueOrDefault(); }
            set { __pbn__Idlesecs = value; }
        }
        public bool ShouldSerializeIdlesecs() => __pbn__Idlesecs != null;
        public void ResetIdlesecs() => __pbn__Idlesecs = null;
        private uint? __pbn__Idlesecs;

        [global::ProtoBuf.ProtoMember(18, Name = @"strong_certificate")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool StrongCertificate
        {
            get { return __pbn__StrongCertificate ?? false; }
            set { __pbn__StrongCertificate = value; }
        }
        public bool ShouldSerializeStrongCertificate() => __pbn__StrongCertificate != null;
        public void ResetStrongCertificate() => __pbn__StrongCertificate = null;
        private bool? __pbn__StrongCertificate;

        [global::ProtoBuf.ProtoMember(19, Name = @"opus")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool Opus
        {
            get { return __pbn__Opus ?? false; }
            set { __pbn__Opus = value; }
        }
        public bool ShouldSerializeOpus() => __pbn__Opus != null;
        public void ResetOpus() => __pbn__Opus = null;
        private bool? __pbn__Opus;

        [global::ProtoBuf.ProtoContract()]
        public partial class Stats : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"good")]
            public uint Good
            {
                get { return __pbn__Good.GetValueOrDefault(); }
                set { __pbn__Good = value; }
            }
            public bool ShouldSerializeGood() => __pbn__Good != null;
            public void ResetGood() => __pbn__Good = null;
            private uint? __pbn__Good;

            [global::ProtoBuf.ProtoMember(2, Name = @"late")]
            public uint Late
            {
                get { return __pbn__Late.GetValueOrDefault(); }
                set { __pbn__Late = value; }
            }
            public bool ShouldSerializeLate() => __pbn__Late != null;
            public void ResetLate() => __pbn__Late = null;
            private uint? __pbn__Late;

            [global::ProtoBuf.ProtoMember(3, Name = @"lost")]
            public uint Lost
            {
                get { return __pbn__Lost.GetValueOrDefault(); }
                set { __pbn__Lost = value; }
            }
            public bool ShouldSerializeLost() => __pbn__Lost != null;
            public void ResetLost() => __pbn__Lost = null;
            private uint? __pbn__Lost;

            [global::ProtoBuf.ProtoMember(4, Name = @"resync")]
            public uint Resync
            {
                get { return __pbn__Resync.GetValueOrDefault(); }
                set { __pbn__Resync = value; }
            }
            public bool ShouldSerializeResync() => __pbn__Resync != null;
            public void ResetResync() => __pbn__Resync = null;
            private uint? __pbn__Resync;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestBlob : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"session_texture")]
        public uint[] SessionTextures { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"session_comment")]
        public uint[] SessionComments { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"channel_description")]
        public uint[] ChannelDescriptions { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ServerConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"max_bandwidth")]
        public uint MaxBandwidth
        {
            get { return __pbn__MaxBandwidth.GetValueOrDefault(); }
            set { __pbn__MaxBandwidth = value; }
        }
        public bool ShouldSerializeMaxBandwidth() => __pbn__MaxBandwidth != null;
        public void ResetMaxBandwidth() => __pbn__MaxBandwidth = null;
        private uint? __pbn__MaxBandwidth;

        [global::ProtoBuf.ProtoMember(2, Name = @"welcome_text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string WelcomeText
        {
            get { return __pbn__WelcomeText ?? ""; }
            set { __pbn__WelcomeText = value; }
        }
        public bool ShouldSerializeWelcomeText() => __pbn__WelcomeText != null;
        public void ResetWelcomeText() => __pbn__WelcomeText = null;
        private string __pbn__WelcomeText;

        [global::ProtoBuf.ProtoMember(3, Name = @"allow_html")]
        public bool AllowHtml
        {
            get { return __pbn__AllowHtml.GetValueOrDefault(); }
            set { __pbn__AllowHtml = value; }
        }
        public bool ShouldSerializeAllowHtml() => __pbn__AllowHtml != null;
        public void ResetAllowHtml() => __pbn__AllowHtml = null;
        private bool? __pbn__AllowHtml;

        [global::ProtoBuf.ProtoMember(4, Name = @"message_length")]
        public uint MessageLength
        {
            get { return __pbn__MessageLength.GetValueOrDefault(); }
            set { __pbn__MessageLength = value; }
        }
        public bool ShouldSerializeMessageLength() => __pbn__MessageLength != null;
        public void ResetMessageLength() => __pbn__MessageLength = null;
        private uint? __pbn__MessageLength;

        [global::ProtoBuf.ProtoMember(5, Name = @"image_message_length")]
        public uint ImageMessageLength
        {
            get { return __pbn__ImageMessageLength.GetValueOrDefault(); }
            set { __pbn__ImageMessageLength = value; }
        }
        public bool ShouldSerializeImageMessageLength() => __pbn__ImageMessageLength != null;
        public void ResetImageMessageLength() => __pbn__ImageMessageLength = null;
        private uint? __pbn__ImageMessageLength;

        [global::ProtoBuf.ProtoMember(6, Name = @"max_users")]
        public uint MaxUsers
        {
            get { return __pbn__MaxUsers.GetValueOrDefault(); }
            set { __pbn__MaxUsers = value; }
        }
        public bool ShouldSerializeMaxUsers() => __pbn__MaxUsers != null;
        public void ResetMaxUsers() => __pbn__MaxUsers = null;
        private uint? __pbn__MaxUsers;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SuggestConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"version")]
        public uint Version
        {
            get { return __pbn__Version.GetValueOrDefault(); }
            set { __pbn__Version = value; }
        }
        public bool ShouldSerializeVersion() => __pbn__Version != null;
        public void ResetVersion() => __pbn__Version = null;
        private uint? __pbn__Version;

        [global::ProtoBuf.ProtoMember(2, Name = @"positional")]
        public bool Positional
        {
            get { return __pbn__Positional.GetValueOrDefault(); }
            set { __pbn__Positional = value; }
        }
        public bool ShouldSerializePositional() => __pbn__Positional != null;
        public void ResetPositional() => __pbn__Positional = null;
        private bool? __pbn__Positional;

        [global::ProtoBuf.ProtoMember(3, Name = @"push_to_talk")]
        public bool PushToTalk
        {
            get { return __pbn__PushToTalk.GetValueOrDefault(); }
            set { __pbn__PushToTalk = value; }
        }
        public bool ShouldSerializePushToTalk() => __pbn__PushToTalk != null;
        public void ResetPushToTalk() => __pbn__PushToTalk = null;
        private bool? __pbn__PushToTalk;

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
